### ISSUE TITLE
Поддержка вложений

### ISSUE THREAD

**Issue by aNNiMON** [NoticEditorTeam/NoticEditor#23]
Реквестирую очень нужную фичу - поддержка вложений. Сохранять можно в base64, так что особых проблем возникнуть не должно.

**Comment by SeTSeR** [comment]
Какие вложения?
В заметку чтоль?

**Comment by aNNiMON** [comment]
@SeTSeR да

**Comment by NaikSoftware** [comment]
Можно внизу сделать панельку для управления файлами, а в разметку вставлять нужно? Будет наверное непросто сделать по нормальному.

**Comment by NaikSoftware** [comment]
Хотя можно при клике на прикрепленный файл вставлять что то типа ![](:file.dat "Inserted file")
а потом что нибудь придумаем что делать с этими ссылками.

**Comment by aNNiMON** [comment]
Вообще, я предлагал изменить формат хранения документов на zip. Иерархия в таком случае отлично поддерживается, все вложения можно хранить в том виде, в котором они есть, а не гонять в base64 и обратно. Также можно будет открывать документы и с Android и Java ME, где программы нет - просто открываешь zip и смотришь .md файлы. Удобно как по мне и не сильно сложно в плане реализации.

**Comment by NaikSoftware** [comment]
можно и так

**Comment by SeTSeR** [comment]
Сегодня/завтра постараюсь это сделать, только дайте время разобраться в коде :D

**Comment by aNNiMON** [comment]
Пока можно пока только картинки, чтоб они прикреплялись в нужном месте на странице. В html тогда будет что-то типа такого: `<img src="data:image/png;base64,iVBORw0KGgoAAAANS...." />`

**Comment by aNNiMON** [comment]
Внезапно!!!
![image](https://cloud.githubusercontent.com/assets/1321838/9093780/c4cd608e-3bb6-11e5-8c39-aa45efd264dc.png)

**Comment by NaikSoftware** [comment]
Ну это понятно, но нужно прикреплять нормально

**Comment by NaikSoftware** [comment]
Вообще markdown сомнительное решение, не проще ли сделать WebView и работать с HTML.

**Comment by aNNiMON** [comment]
@NaikSoftware нет. Markdown удобен тем, что его можно открыть на чём угодно. Вот, например, я на Dropbox'e создал заметку и могу в любой момент открыть её на ПК или на андроиде. Если мне надо будет перегнать заметку в другой формат (те же BB-codes), я сделаю это проще с md, чем с html.

**Comment by NaikSoftware** [comment]
Короче @SeTSeR пусть переделывает в zip, только пусть сами заметки не трогает, в json пусть остаются, запихнуть только в архив как ```notices.json``` и папку ```res/``` в архиве для вложений

**Comment by aNNiMON** [comment]
@NaikSoftware а смысл сохранять json в zip? json - поддерживает древовидную структуру, zip - тоже. Излишне же. И с мобилы не прочитать никак тогда.

**Comment by NaikSoftware** [comment]
А смысл с мобилы читать? Парсер пишется за 10 минут

**Comment by aNNiMON** [comment]
Неохота держать приложение, чтобы почитать заметки, если можно обойтись обычным текстовым редактором.

Я храню инфу вот такого рода [git.json](https://www.dropbox.com/s/wdmkirte2trbtet/git.json?dl=0) на дропбоксе. Иногда нужно с мобилки заглянуть и прочесть заметку. Так вот удобнее это будет сделать, скачав zip-архив и открыв md-файл.

**Comment by NaikSoftware** [comment]
Ну делайте так, но придется опять переписывать? Кстати имя заметки для названия папок плохая идея - коллизии + запрещенные символы + кодировки - много проблем

**Comment by aNNiMON** [comment]
@NaikSoftware твой id надо переделать. Неудобно искать где какой номер соответствует нужной заметке. Вроде ж коллизию разрешить не сложно? Да банально:

```java
try {
    save(item.getTitle());
} catch (IOException ioe) {
    save(item.getId());
}
```

**Comment by NaikSoftware** [comment]
@aNNiMON в архиве лучше все таки не хранить по именам. Не раз встречал глюки, не распаковывалось, при кирилических названиях в архиве. 

Цифровой id подходит нормально для того что я его делал - хтмл. Там открываешь index.html и все ссылки там с норм. именами, а файл с непонятным)

**Comment by SeTSeR** [comment]
https://github.com/TemporaryTeam/NoticEditor/issues/23#issuecomment-128118838
Даже больше скажу, её не должно возникать
Разве что кто-то создаст в одной ветке две заметки с одинаковым именем
И всё же, что именно надо сделать?

**Comment by NaikSoftware** [comment]
Конечно создаст :)

Можешь написать хранение заметок вместо json в zip. 
Где имя файла или папки - это имя заметки или ветки.

Но я против такой штуки.
[ ] Не все имена можно использовать в качестве имени файла (спецсимволы, все дела)
[ ] Могут быть проблемы с кодировкой в архиве
[ ] Возможны коллизии имен, ну ок, сохраним с другим именем как пишет @aNNiMON , но таким образом мы изменим и имя заметки!
[ ] В конце концов это нерасширяемо - если нам понадобится хранить еще что-то в заметке кроме имени, детей и контента, то его некуда засунуть. В json - просто добавить поле, будет даже обратная совместимость таким образом.
[ ] json просто распарсить либами, архив нужно разбирать/собирать вручную.

**Comment by SeTSeR** [comment]
Есть ещё один вариант, но его надо сначала продумать мне

**Comment by SeTSeR** [comment]
Надо как-то совместить удобство использования и расширяемость

**Comment by SeTSeR** [comment]
https://github.com/TemporaryTeam/NoticEditor/issues/23#issuecomment-128156640
Ну так если создаст - как сам различать будет?

**Comment by NaikSoftware** [comment]
В файле, котором хранится заметки удобство должно быть для разработчиков) Для юзеров есть экспорт в хтмл, в архив и можно сделать просто в файлы md

**Comment by SeTSeR** [comment]
Одинаковые имена для заметки и ветки разрешить можно, а для заметок имхо лучше запретить.
Формат заметок я менять и не предлагал.

**Comment by aNNiMON** [comment]
Насчёт имён, можно было бы в zip создавать специальный файл с описанием всей структуры документа.

```json
{"title":"note:きゃりーぱ123", "filename":"note_u304du3083u308au30fcu3071123"}
```

тогда и читать структуру можно будет из этого файла. Заодно и различать документ NoticEditor от обычного zip.


@NaikSoftware с папкой `resources` ровно те же косяки. Закину я файл 1.png, а потом ещё один с таким именем в другую заметку и - коллизия.

**Comment by aNNiMON** [comment]
@NaikSoftware [*В файле, котором хранится заметки удобство должно быть для разработчиков*](https://github.com/TemporaryTeam/NoticEditor/issues/23#issuecomment-128159980)

Тут ты прав, json - удобный в этом плане, отказываться от него не нужно.

**Comment by NaikSoftware** [comment]
@aNNiMON, хм, если мы будем хранить в файле со структурой ссылки на файлы со сгеннрироваными именами, то какой тогда смысл выносить их в отдельные файлы? Читать на дропбоксе так получится, из-за этого? С прикрепленными файлами так и нужно будет сделать, их то точно не в json хранить.

**Comment by aNNiMON** [comment]
@NaikSoftware да, вроде неплохо. Но пока мы это сделаем.. Легче привыкнуть сохранять json и экспортировать в zip, чтоб в случае чего можно было открыть с любого устройства.

**Comment by SeTSeR** [comment]
Ну а как тогда с вложениями-то?

**Comment by aNNiMON** [comment]
@SeTSeR пусть в base64 кодируются, а при экспорте в zip создаётся папка resources и там это в бинарник пусть конвертируется.

**Comment by SeTSeR** [comment]
Жуть O_O

**Comment by SeTSeR** [comment]
Не знаю, когда начну этим заниматься

**Comment by aNNiMON** [comment]
@NaikSoftware 
> https://github.com/TemporaryTeam/NoticEditor/pull/26#issuecomment-128394743
> Вроде остановились на json в zip, но контент вынести в файлы md с именами 1, 2, 3 и т.д.
Ресурсы также. Пока что ничего лучше не придумал

Да, но что делать с ресурсами? Искать их в одной папке resources не очень удобно, тем более, если это надо сделать с телефона. И остаётся проблема с именами.

Может лучше всё-таки на каждую заметку свою папку создавать и туда ресурсы? Префиксом отделять ветку от заметки. Обойтись без 1, 2, 3, а делать конвертацию имён, а в случае с одинаковыми заметками - добавлять индекс.

```
file.zip
    branch_first/
        note_mynote/
            mynote.md
            photo.jpg
            image.png
        branch_second/
            note_note/
                ...
            note_note_1/
            note_note_2/
    notices.json
```

**Comment by NaikSoftware** [comment]
Да мне в принципе все равно, главное чтоб в json хранились все путя, а там как вам удобно.. Я вручную смотреть эти заметки все равно не буду

**Comment by SeTSeR** [comment]
Я так понял, что я уже могу ничего не предлагать - всё равно скорее всего не реализую(не успею/etc) :)

**Comment by aNNiMON** [comment]
Сделал сохранение в zip с индексным файлом и конвертацией имён заметок.
https://github.com/aNNiMON/NoticEditor/tree/new-format

Pull Request пока не создаю, нужно ещё открытие сделать. Если есть какие-то замечания, говорите, пока не поздно.

**Comment by NaikSoftware** [comment]
@aNNiMON отлично, хорошо что почистил контроллер. Сольешь эти изменения? Там вроде экспорт в HTML только затронут.

**Comment by mrEDitor** [comment]
Так как там с вложениями? Заглохли? Просто прикладывать бы файлы как ссылки для распаковки пользователем для начала неплохо бы. А там можно будет и больше прикрутить.

Предлагаю:
* Складывать вместе с заметками в файловое дерево, позволять добавлять файлы в любой узел (корень, ветку, заметку), чтобы их было видно из всех наследников. Думаю, что в самом простом варианте пользователь будет добавлять файл к заметке, а остальное уже будет чуть сложнее, но вполне достижимо для "прошаренного" пользователя.
* Именовать файлы в архиве по тому же принципу, что и заметки.
* Именовать файлы при ссылке в заметке реальными именами в архиве с указанием пути вверх по необходимости (file_image1.png, ../file_image3.jpg, и т.д., чтобы было проще с поиском вручную), но не разрешать переход в соседнюю ветку (../neighbor/file.png, потому что файл вместе с заметкой/веткой удаляется (?)).
* Фиксировать адреса и оригинальные имена файлов в JSON'е.

**Comment by SeTSeR** [comment]
По поводу вложений. Добавлять их в произвольное место или только в конец?

**Comment by SeTSeR** [comment]
Так, кое-какое прикрепление изображений есть. Теперь надо разобраться с сохранением

**Comment by aNNiMON** [comment]
Ты ж в base64 сделал, так что никакой разницы нет сейчас, что в JSON, что в ZIP.

Да и вообще, экспорт в zip отличается лишь тем, что сам текст заметки идёт не в index.json, а в md, так что список вложений и вообще всё, что угодно можно в index.json класть.

**Comment by SeTSeR** [comment]
Я думал, в зипе отдельно вложения хранить, чтобы потом глянуть можно было

Тогда закрываю?

**Comment by aNNiMON** [comment]
Как будут вложения любых файлов, тогда можно будет подумать. А пока и так нормально. :+1: 

Не, оставь, наверное.

**Comment by aNNiMON** [comment]
60581871648b129f5dad0623f1c7a19f58335a2b

В двух словах опишу, что сделал, чтоб лишний раз по коду не разбирались.

Для JSON вложения перекодируются в base64 и записываются в массив attachments у каждой заметки

```
note: {
 ...
 attachments : [
    [name : file.png, data : base64encodedstring...],
    [name : 1.mp3, data : base64encodedstring...]
 ]
}
```

При чтении, соответственно, декодируем строку в массив байт.

----

Для ZIP точно так же, записывается массив attachments, только поля data нет, а содержимое сохраняется как файл с оригинальным именем в той папке, где у нас сама заметка. Имя файла прогоняется через sanitize, так что проблем с архивом и распаковкой не будет.

При чтении, данные берём непосредственно из файла.

----

Если вложение - картинка, в редактор вставляется специальная ссылка `@att:file.png`, которая при парсинге md заменяется на img с base64 содержимым. Синтаксис этой ссылки выбрали на скорую руку, так что до того, как сольём ветку, можете предлагать свои варианты.

TODO (отсортировано от лёгкого к сложному):

- [ ] обработку `@att` наверное лучше делать после парсинга md, чтоб не тормозить его большим объёмом текста.

- [ ] не обрабатываются ситуации, когда добавляются вложения с одинаковым именем (тут же можно и дубли отсеять)

- [ ] я забыл сделать учёт старых документов, где не было поля attachment, так что надо этот момент обработать, добавив проверку на существование этого поля в json.

- [ ] вставлять `@att` в место под курсором, либо сразу выделять его при вставке, чтоб можно было быстро вырезать и переместить куда надо.

- [ ] срочно нужна гуишка для вложений. @mrEDitor делал вкладки в окне редактора, вот туда, пожалуй, и надо список встроить.

 - [ ] обязательный функционал: удаление вложения и сохранение как файл. Поясню за второе. Если мы сохраняем заметку в json, то все вложения у нас в base64 и нужно как-то их доставать, ту же музыку прослушать или файл проекта получить.

 - [ ] необязательно, но хотелось бы видеть в панели вложений и drag'n'drop. ~~но я-то знаю, что никто не сделает~~
