### ISSUE TITLE
Документирование

### ISSUE THREAD

**Issue by NaikSoftware** [NoticEditorTeam/NoticEditor#35]
Прошел день, тут накоммитили много всего. Появились новые классы. Если у @aNNiMON  в сохранялке более менее все ясно, то зачем нужны. NoticeTree, если для дерева достаточно двух элементов - root, current. NoticeTree наверное имеет право на жизнь, но оно не интегрировано в программу. Ноды удаляются и добавляются без участия NoticeTree, он просто прилеплен..
NoticeTreeView вообще не используется.

Просьба писать в доках или хотябы в пул реквестах что оно и зачем, чтоб не рыть весь код в поисках использования. Возможно вы планируете как то использовать эти классы в будущем?

**Comment by aNNiMON** [comment]
Тут, скорее, вопрос понятности.
`NoticeTreeItem root, current;` мало о чём может сказать, а вот
```java
Notice tree tree;
NoticeTreeItem current;
```
уже говорит о том, что у нас есть дерево. А в этом дереве будут собраны методы, которые влияют на работу этого самого дерева. В итоге мы сразу знаем где хранится нужный нам метод, и не придётся его искать по контроллерам и другим классам.

**Comment by NaikSoftware** [comment]
Согласен, но он не используется. Нужно же код обновить/переделать.

Та же история с  NoticeTreeView - просто пустой класс

**Comment by SeTSeR** [comment]
Собственно, на основе этих классов я хочу создать биндинги для разных ЯПов

**Comment by SeTSeR** [comment]
Кроме того, ведётся работа над перепиливанием алгоритмов на работу с целым деревом и устранением рекурсии

**Comment by NaikSoftware** [comment]
имхо модули нужны для системы редактирования заметки, и в той либе уже есть поддержка модулей написанных на java и scala, дерево им не нужно
