### ISSUE TITLE
Support importing articles from web

### ISSUE THREAD

**Issue by xamgore** [NoticEditorTeam/NoticEditor#43]
We really need this feature! :+1:

**Comment by NaikSoftware** [comment]
Give me webserver!

**Comment by NaikSoftware** [comment]
You can load article from Internet via JS (and save code with link in notice)
![2015-08-12 18 06 09](https://cloud.githubusercontent.com/assets/4218994/9227573/001e499e-411d-11e5-85b4-485ea84c1c6e.png)

**Comment by aNNiMON** [comment]
@NaikSoftware killer feature :smiley:

**Comment by NaikSoftware** [comment]
Mission complete, but my code is too old relatively to you and can't be merged :(
https://vk.com/doc87875878_412646199
![2015-08-12 21 23 52](https://cloud.githubusercontent.com/assets/4218994/9232814/767643ec-4138-11e5-892a-729b69954c70.png)

**Comment by aNNiMON** [comment]
@NaikSoftware maybe @xamgore means automatically parse article content from page like [Readable](http://readable.tastefulwords.com/)? 

You should use separate branch for all additions and do not merge your changes with `master` while your pool request not fully merged. But now you can rename your `master` branch and pull changes from this `master`.

**Comment by NaikSoftware** [comment]
@aNNiMON, Unlikely, would be fat. 

P.S. my changes have conflicts, I will develop in separate fork

**Comment by aNNiMON** [comment]
@NaikSoftware you can revert or remove your changes.

`git revert commitId`
`git reset --hard commitId && git push --force`

or move them from master to new branch via `git rebase`

**Comment by NaikSoftware** [comment]
Та это понятно что можно удалить/открыть новую ветку, но что-то не охота терять изменения. Sorry for my english

**Comment by aNNiMON** [comment]
Да ты и не потеряешь. Во-первых, говорю ж, ты можешь ветку переименовать и оставить. Если что, можешь потом обратно переключиться на неё или посмотреть diff.
Во-вторых, ты можешь экспортировать изменения в diff-файл. А потом взять что-нибудь оттуда.
А ещё, в-третьих, ты можешь выполнить первый шаг и потом взять `cherry pick`ом нужный коммит и подлить в мастер.

**Comment by NaikSoftware** [comment]
Ок, что нибудь попробую.

**Comment by xamgore** [comment]
What is the progress, guys?

**Comment by NaikSoftware** [comment]
@xamgore, you can import web page as html, norm?

**Comment by riseremi** [comment]
I think not. We need to strip html tags and turn this
```
<html>
  <head>
    <title>NoticEditor</title>
  <head>
  <body>
    <article>
      I tried to <strong>shave</strong> myself, but I <em>failed</em>
    </article>
  </body>
</html>
```
into this
```
I tried to shave myself, but I failed
```

If NoticEditor supports text styling, we should also process **strong** and *italic* tags.

If you have no time atm, just cut everything between <body> and </body>, it will be enough.

**Comment by NaikSoftware** [comment]
@riseremi , strip html tags supported in this fork https://github.com/NaikSoftware/TreeNote
(see class https://github.com/NaikSoftware/TreeNote/blob/master/src/com/temporaryteam/treenote/importer/WebImporter.java)
You can implement it in upstream if you want

**Comment by riseremi** [comment]
Wow! Have you already implemented this?

**Comment by SeTSeR** [comment]
@riseremi, we have
