### ISSUE TITLE
Примеры файлов

### ISSUE THREAD

**Issue by White-Oak** [NoticEditorTeam/NoticEditor#52]
Создайте примеры файлов где-нибудь в папке /examples, чтобы можно было посмотреть, как оно всё работает-то

**Comment by aNNiMON** [comment]
@White-Oak, https://www.dropbox.com/s/sy0er82d9jd0qwo/git.zip?dl=0

**Comment by White-Oak** [comment]
@aNNiMON нет, ну, спасибо, а в самом репо? :)

**Comment by aNNiMON** [comment]
@White-Oak ну в репо такое добавлять как-то, не знаю, незачем.

**Comment by White-Oak** [comment]
@aNNiMON Лол, ну а куда еще?

**Comment by NaikSoftware** [comment]
в справку программы вынести синтаксис markdown и написать что можно использовать html + js

**Comment by White-Oak** [comment]
Ну смысл в том, чтобы пользователь сразу увидел на что способна программа -- работу с древовидными заметками.

**Comment by White-Oak** [comment]
Почему это закрыто? Проблема была решена?

**Comment by White-Oak** [comment]
Коммит закрывающий проблему: https://github.com/NoticEditorTeam/NoticEditor/commit/7d6a0aedf4d90206010db4d894570e102d6ce8ad
